apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: esyfo-pdfgen-demo-web
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /internal/is_alive
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 128Mi
  ingresses:
    - https://esyfo-pdfgen-demo.intern.dev.nav.no
  azure:
    application:
      enabled: true
      tenant: nav.no
      allowAllUsers: true
    sidecar:
      enabled: true
      autoLogin: true
  accessPolicy:
    outbound:
      rules:
        - application: esyfo-pdfgen-demo
